### ISSUE TITLE
Do you any algorithm on C Sharp (C#)?

### ISSUE THREAD

**Issue by abrahamcalf** [AllAlgorithms/csharp#3]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [C Sharp (C#)](https://github.com/AllAlgorithms/csharp) this case

**Comment by curranlipsett** [comment]
I could add a Fibonacci example, would that be a valuable addition?
